//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPqDASRUnitTest {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestsReferences {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestsReferences() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CPqDASRUnitTest.TestsReferences", typeof(TestsReferences).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 8K\ContinuosMode\joao_mineiro_marciano_intro_8k.wav.
        /// </summary>
        internal static string AudioContinuosMode {
            get {
                return ResourceManager.GetString("AudioContinuosMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 8K\CPF\cpf_8k.wav.
        /// </summary>
        internal static string AudioCpf {
            get {
                return ResourceManager.GetString("AudioCpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 8K\pizza\pizza_veg_audio_8k.wav.
        /// </summary>
        internal static string AudioPizzaVeg {
            get {
                return ResourceManager.GetString("AudioPizzaVeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 8K\Silencio\silence-8k.wav.
        /// </summary>
        internal static string AudioSilence {
            get {
                return ResourceManager.GetString("AudioSilence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a wss://speech.cpqd.com.br/asr/ws/estevan/recognize/8k.
        /// </summary>
        internal static string DefaultASRURL {
            get {
                return ResourceManager.GetString("DefaultASRURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a builtin:slm/general.
        /// </summary>
        internal static string FreeLanguageModel {
            get {
                return ResourceManager.GetString("FreeLanguageModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a http://vmh102.cpqd.com.br:8280/asr_dist/repository/grammars/dynamic-gram/pizza.gram.
        /// </summary>
        internal static string GramPizzaHttp {
            get {
                return ResourceManager.GetString("GramPizzaHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ws://vmh123.cpqd.com.br:8025/asr-server/asr.
        /// </summary>
        internal static string InternalASRURL {
            get {
                return ResourceManager.GetString("InternalASRURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a pizza_vegetariana.
        /// </summary>
        internal static string InterpPizzaVeg {
            get {
                return ResourceManager.GetString("InterpPizzaVeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a você me pede na carta que diz apareça.
        /// </summary>
        internal static string TextContinuousModeSeg1 {
            get {
                return ResourceManager.GetString("TextContinuousModeSeg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a que eu nunca mais te procure para sempre te esqueça.
        /// </summary>
        internal static string TextContinuousModeSeg2 {
            get {
                return ResourceManager.GetString("TextContinuousModeSeg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a posso fazer essa vontade de atender seu pedido.
        /// </summary>
        internal static string TextContinuousModeSeg3 {
            get {
                return ResourceManager.GetString("TextContinuousModeSeg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a eu quero uma pizza vegetariana.
        /// </summary>
        internal static string TextPizzaVeg {
            get {
                return ResourceManager.GetString("TextPizzaVeg", resourceCulture);
            }
        }
    }
}
