//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPqDASRUnitTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestsReferences {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestsReferences() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CPqDASRUnitTest.TestsReferences", typeof(TestsReferences).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8K\ContinuosMode\joao_mineiro_marciano_intro_8k.wav.
        /// </summary>
        internal static string AudioContinuosMode {
            get {
                return ResourceManager.GetString("AudioContinuosMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8K\CPF\cpf_8k.wav.
        /// </summary>
        internal static string AudioCpf {
            get {
                return ResourceManager.GetString("AudioCpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8K\pizza\pizza_veg_audio_8k.wav.
        /// </summary>
        internal static string AudioPizzaVeg {
            get {
                return ResourceManager.GetString("AudioPizzaVeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8K\Silencio\silence-8k.wav.
        /// </summary>
        internal static string AudioSilence {
            get {
                return ResourceManager.GetString("AudioSilence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wss://speech.cpqd.com.br/asr/ws/v2/recognize/8k.
        /// </summary>
        internal static string DefaultASRURL {
            get {
                return ResourceManager.GetString("DefaultASRURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to builtin:slm/general.
        /// </summary>
        internal static string FreeLanguageModel {
            get {
                return ResourceManager.GetString("FreeLanguageModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vmh102.cpqd.com.br:8280/asr_dist/repository/grammars/dynamic-gram/pizza.gram.
        /// </summary>
        internal static string GramPizzaHttp {
            get {
                return ResourceManager.GetString("GramPizzaHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wss://speech.cpqd.com.br/asr/ws/v2/recognize/8k.
        /// </summary>
        internal static string InternalASRURL {
            get {
                return ResourceManager.GetString("InternalASRURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pizza_vegetariana.
        /// </summary>
        internal static string InterpPizzaVeg {
            get {
                return ResourceManager.GetString("InterpPizzaVeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8K\Nasceu\nasceu.pcm.
        /// </summary>
        internal static string Nasceu {
            get {
                return ResourceManager.GetString("Nasceu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dummy.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to você me pede na carta que diz apareça.
        /// </summary>
        internal static string TextContinuousModeSeg1 {
            get {
                return ResourceManager.GetString("TextContinuousModeSeg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to que eu nunca mais te procure para sempre te esqueça.
        /// </summary>
        internal static string TextContinuousModeSeg2 {
            get {
                return ResourceManager.GetString("TextContinuousModeSeg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to posso fazer essa vontade de atender seu pedido.
        /// </summary>
        internal static string TextContinuousModeSeg3 {
            get {
                return ResourceManager.GetString("TextContinuousModeSeg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 728934251-11.
        /// </summary>
        internal static string TextCPFTextify {
            get {
                return ResourceManager.GetString("TextCPFTextify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a minha filha nasceu hoje ela tem dez anos.
        /// </summary>
        internal static string TextNasceu {
            get {
                return ResourceManager.GetString("TextNasceu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eu quero uma pizza vegetariana.
        /// </summary>
        internal static string TextPizzaVeg {
            get {
                return ResourceManager.GetString("TextPizzaVeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dummy.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
